//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.CodeDom.Compiler;
using System.ComponentModel;
using System.Diagnostics;
using System.Diagnostics.CodeAnalysis;
using System.Globalization;
using System.Resources;
using System.Runtime.CompilerServices;

namespace ActiveLogin.Authentication.BankId.AspNetCore.Resources
{
    /// <summary>
    ///     A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [GeneratedCode("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [DebuggerNonUserCode()]
    [CompilerGenerated()]
    internal class BankIdAuthenticationHandler
    {
        private static ResourceManager resourceMan;

        private static CultureInfo resourceCulture;

        [SuppressMessage("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal BankIdAuthenticationHandler()
        {
        }

        /// <summary>
        ///     Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [EditorBrowsable(EditorBrowsableState.Advanced)]
        internal static ResourceManager ResourceManager
        {
            get
            {
                if (ReferenceEquals(resourceMan, null))
                {
                    ResourceManager temp = new ResourceManager(
                        "ActiveLogin.Authentication.BankId.AspNetCore.Resources.BankIdAuthenticationHandle" +
                        "r", typeof(BankIdAuthenticationHandler).Assembly);
                    resourceMan = temp;
                }

                return resourceMan;
            }
        }

        /// <summary>
        ///     Overrides the current thread's CurrentUICulture property for all
        ///     resource lookups using this strongly typed resource class.
        /// </summary>
        [EditorBrowsable(EditorBrowsableState.Advanced)]
        internal static CultureInfo Culture
        {
            get { return resourceCulture; }
            set { resourceCulture = value; }
        }

        /// <summary>
        ///     Looks up a localized string similar to Start your BankID app..
        /// </summary>
        internal static string BankIdUserMessage_ShortName_RFA1
        {
            get { return ResourceManager.GetString("BankIdUserMessage_ShortName_RFA1", resourceCulture); }
        }

        /// <summary>
        ///     Looks up a localized string similar to Trying to start your BankID app..
        /// </summary>
        internal static string BankIdUserMessage_ShortName_RFA13
        {
            get { return ResourceManager.GetString("BankIdUserMessage_ShortName_RFA13", resourceCulture); }
        }

        /// <summary>
        ///     Looks up a localized string similar to Searching for BankID:s, it may take a little while… If a few seconds have
        ///     passed and still no BankID has been found, you probably don’t have a BankID which can be used for this
        ///     login/signature on this computer. If you have a BankID card, please insert it into your card reader. If you don’t
        ///     have a BankID you can order one from your internet bank. If you have a BankID on another device you can start the
        ///     BankID app on that device..
        /// </summary>
        internal static string BankIdUserMessage_ShortName_RFA14A
        {
            get { return ResourceManager.GetString("BankIdUserMessage_ShortName_RFA14A", resourceCulture); }
        }

        /// <summary>
        ///     Looks up a localized string similar to Searching for BankID:s, it may take a little while… If a few seconds have
        ///     passed and still no BankID has been found, you probably don’t have a BankID which can be used for this
        ///     login/signature on this device. If you don’t have a BankID you can order one from your internet bank. If you have a
        ///     BankID on another device you can start the BankID app on that device..
        /// </summary>
        internal static string BankIdUserMessage_ShortName_RFA14B
        {
            get { return ResourceManager.GetString("BankIdUserMessage_ShortName_RFA14B", resourceCulture); }
        }

        /// <summary>
        ///     Looks up a localized string similar to Searching for BankID:s, it may take a little while… If a few seconds have
        ///     passed and still no BankID has been found, you probably don’t have a BankID which can be used for this
        ///     login/signature on this computer. If you have a BankID card, please insert it into your card reader. If you don’t
        ///     have a BankID you can order one from your internet bank..
        /// </summary>
        internal static string BankIdUserMessage_ShortName_RFA15A
        {
            get { return ResourceManager.GetString("BankIdUserMessage_ShortName_RFA15A", resourceCulture); }
        }

        /// <summary>
        ///     Looks up a localized string similar to Searching for BankID:s, it may take a little while… If a few seconds have
        ///     passed and still no BankID has been found, you probably don’t have a BankID which can be used for this
        ///     login/signature on this device. If you don’t have a BankID you can order one from your internet bank..
        /// </summary>
        internal static string BankIdUserMessage_ShortName_RFA15B
        {
            get { return ResourceManager.GetString("BankIdUserMessage_ShortName_RFA15B", resourceCulture); }
        }

        /// <summary>
        ///     Looks up a localized string similar to The BankID you are trying to use is revoked or too old. Please use another
        ///     BankID or order a new one from your internet bank..
        /// </summary>
        internal static string BankIdUserMessage_ShortName_RFA16
        {
            get { return ResourceManager.GetString("BankIdUserMessage_ShortName_RFA16", resourceCulture); }
        }

        /// <summary>
        ///     Looks up a localized string similar to The BankID app couldn’t be found on your computer or mobile device. Please
        ///     install it and order a BankID from your internet bank. Install the app from install.bankid.com..
        /// </summary>
        internal static string BankIdUserMessage_ShortName_RFA17
        {
            get { return ResourceManager.GetString("BankIdUserMessage_ShortName_RFA17", resourceCulture); }
        }

        /// <summary>
        ///     Looks up a localized string similar to Start the BankID app.
        /// </summary>
        internal static string BankIdUserMessage_ShortName_RFA18
        {
            get { return ResourceManager.GetString("BankIdUserMessage_ShortName_RFA18", resourceCulture); }
        }

        /// <summary>
        ///     Looks up a localized string similar to Would you like to login or sign with a BankID on this computer or with a
        ///     Mobile BankID?.
        /// </summary>
        internal static string BankIdUserMessage_ShortName_RFA19
        {
            get { return ResourceManager.GetString("BankIdUserMessage_ShortName_RFA19", resourceCulture); }
        }

        /// <summary>
        ///     Looks up a localized string similar to The BankID app is not installed. Please contact your internet bank..
        /// </summary>
        internal static string BankIdUserMessage_ShortName_RFA2
        {
            get { return ResourceManager.GetString("BankIdUserMessage_ShortName_RFA2", resourceCulture); }
        }

        /// <summary>
        ///     Looks up a localized string similar to Would you like to login or sign with a BankID on this device or with a
        ///     BankID on another device?.
        /// </summary>
        internal static string BankIdUserMessage_ShortName_RFA20
        {
            get { return ResourceManager.GetString("BankIdUserMessage_ShortName_RFA20", resourceCulture); }
        }

        /// <summary>
        ///     Looks up a localized string similar to Login or signing in progress..
        /// </summary>
        internal static string BankIdUserMessage_ShortName_RFA21
        {
            get { return ResourceManager.GetString("BankIdUserMessage_ShortName_RFA21", resourceCulture); }
        }

        /// <summary>
        ///     Looks up a localized string similar to Unknown error. Please try again..
        /// </summary>
        internal static string BankIdUserMessage_ShortName_RFA22
        {
            get { return ResourceManager.GetString("BankIdUserMessage_ShortName_RFA22", resourceCulture); }
        }

        /// <summary>
        ///     Looks up a localized string similar to Action cancelled. Please try again..
        /// </summary>
        internal static string BankIdUserMessage_ShortName_RFA3
        {
            get { return ResourceManager.GetString("BankIdUserMessage_ShortName_RFA3", resourceCulture); }
        }

        /// <summary>
        ///     Looks up a localized string similar to An identification or signing for this personal number is already started.
        ///     Please try again..
        /// </summary>
        internal static string BankIdUserMessage_ShortName_RFA4
        {
            get { return ResourceManager.GetString("BankIdUserMessage_ShortName_RFA4", resourceCulture); }
        }

        /// <summary>
        ///     Looks up a localized string similar to Internal error. Please try again..
        /// </summary>
        internal static string BankIdUserMessage_ShortName_RFA5
        {
            get { return ResourceManager.GetString("BankIdUserMessage_ShortName_RFA5", resourceCulture); }
        }

        /// <summary>
        ///     Looks up a localized string similar to Action cancelled..
        /// </summary>
        internal static string BankIdUserMessage_ShortName_RFA6
        {
            get { return ResourceManager.GetString("BankIdUserMessage_ShortName_RFA6", resourceCulture); }
        }

        /// <summary>
        ///     Looks up a localized string similar to The BankID app is not responding. Please check that the program is started
        ///     and that you have internet access. If you don’t have a valid BankID you can get one from your bank. Try again..
        /// </summary>
        internal static string BankIdUserMessage_ShortName_RFA8
        {
            get { return ResourceManager.GetString("BankIdUserMessage_ShortName_RFA8", resourceCulture); }
        }

        /// <summary>
        ///     Looks up a localized string similar to Enter your security code in the BankID app and select Identify or Sign..
        /// </summary>
        internal static string BankIdUserMessage_ShortName_RFA9
        {
            get { return ResourceManager.GetString("BankIdUserMessage_ShortName_RFA9", resourceCulture); }
        }

        /// <summary>
        ///     Looks up a localized string similar to Personal Identity Number.
        /// </summary>
        internal static string PersonalIdentityNumber_Label
        {
            get { return ResourceManager.GetString("PersonalIdentityNumber_Label", resourceCulture); }
        }

        /// <summary>
        ///     Looks up a localized string similar to Sign in.
        /// </summary>
        internal static string SignIn_Button
        {
            get { return ResourceManager.GetString("SignIn_Button", resourceCulture); }
        }

        /// <summary>
        ///     Looks up a localized string similar to BankID.
        /// </summary>
        internal static string SignIn_Header
        {
            get { return ResourceManager.GetString("SignIn_Header", resourceCulture); }
        }

        /// <summary>
        ///     Looks up a localized string similar to YYMMDD-XXXX.
        /// </summary>
        internal static string SignIn_SwedishPersonalIdentityNumber_Placeholder
        {
            get
            {
                return ResourceManager.GetString("SignIn_SwedishPersonalIdentityNumber_Placeholder", resourceCulture);
            }
        }

        /// <summary>
        ///     Looks up a localized string similar to Sign in with BankID.
        /// </summary>
        internal static string SignIn_Title
        {
            get { return ResourceManager.GetString("SignIn_Title", resourceCulture); }
        }

        /// <summary>
        ///     Looks up a localized string similar to Your browser does not have the features required to use this login page..
        /// </summary>
        internal static string UnsupportedBrowser_ErrorMessage
        {
            get { return ResourceManager.GetString("UnsupportedBrowser_ErrorMessage", resourceCulture); }
        }
    }
}
