name: Docs

on:
  push:
    branches:
    - main
    paths:
    - src/**
    - docs/**
    - .github/workflows/docs.yml
  pull_request:
    branches:
    - main
    paths:
    - docs/**
    - .github/workflows/docs.yml
  workflow_dispatch:

jobs:
  generate-docs:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2

    - name: Setup .NET 6.0
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x

    - name: Setup DocFX
      uses: crazy-max/ghaction-chocolatey@v1
      with:
        args: install docfx

    - name: Copy *.md to docs
      run: Copy-Item -Path ./*.md -Destination ./docs/articles
      shell: pwsh

    - name: Fix paths for Readme
      run: (Get-Content ./docs/articles/README.md).replace('docs/articles/', '') | Set-Content ./docs/articles/README.md
      shell: pwsh

    - name: DocFX Build
      working-directory: docs
      run: docfx .\docfx.json
      continue-on-error: false

    - name: Publish
      if: github.event_name == 'push'
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: docs/_site
        force_orphan: true
        cname: docs.activelogin.net
