name: Release

on:
  workflow_run:
    workflows: [Build]
    types:
      - completed
    branches: [main, v*]

jobs:
  release_nuget_to_github_packages:
    name: Release
    runs-on: ubuntu-latest
    environment: GitHubPackages
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    permissions:
      actions: read
      packages: write
    strategy:
      matrix:
        package:
        - ActiveLogin.Authentication.BankId.Api
        - ActiveLogin.Authentication.BankId.Core
        - ActiveLogin.Authentication.BankId.AspNetCore
        - ActiveLogin.Authentication.BankId.AzureKeyVault
        - ActiveLogin.Authentication.BankId.AzureMonitor
        - ActiveLogin.Authentication.BankId.QRCoder
        - ActiveLogin.Authentication.BankId.UAParser
    steps:
      - name: 'Download artifact'
        uses: actions/download-artifact@v4
        with:
          name: activelogin-authentication-nuget-windows
          run-id: ${{ github.event.workflow_run.id }}
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup .NET Core SDK
        uses: actions/setup-dotnet@v4
          
      - name: Add GitHub NuGet source
        run: dotnet nuget add source --username USERNAME --password ${{ secrets.GITHUB_TOKEN }} --store-password-in-clear-text --name github "https://nuget.pkg.github.com/ActiveLogin/index.json"

      - name: Push NuGet packages
        run: dotnet nuget push "ci/${{ matrix.package }}.?.*.nupkg" --skip-duplicate --source "github"
